version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g @angular/cli@9.0.6
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build --prod
    finally:
      - echo final block echo
      
artifacts:
  files:
    - '**/*'
  base-directory: build
